site_name: Viktor Malyi - Practical AI Leadership
site_url: https://vmalyi.com
site_description: "Practical insights on building production AI systems from 16 years in tech and 8 years in AI/ML. Learn from real-world experience leading AI platform teams, deploying 5 production systems, and driving organizational AI adoption. Technical articles, case studies, and speaking topics on AI implementation."
site_author: Viktor Malyi

theme:
  name: shadcn
  show_title: true
  icon: null
  custom_dir: overrides

plugins:
  - search:
      indexing: 'full'
      lang: en
      min_search_length: 2
  - rss:
      match_path: "blog/*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
      categories:
        - tags
      feed_ttl: 1440
      length: 1000
      pretty_print: true
      feed_description: "Practical AI implementation insights from Viktor Malyi"

nav:
  - Start: index.md
  - Consulting: consulting.md
  - Blog: blog/index.md
  - Courses: courses/index.md
  - Speaking: speaking/index.md
  - About: about.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs/snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: false